### ISSUE TITLE
例子

### ISSUE THREAD

**Issue by speakstone** [facebookresearch/Noresqa#1]
您好，对于输入数据格式，可否给一个测试案例？

**Comment by JohnHerry** [comment]
你可以简单测试一个音频做样板语音的。样板语音就是那个 nmr参数指定的东东啊。看main.py, 代码非常简单。 如果你有一堆干净高音质的样板语音，就把它们文件路径列到一个文本文件里，文本文件作为 --nmr的输入参数值。

**Comment by zhangshengnan96** [comment]
> 你可以简单测试一个音频做样板语音的。样板语音就是那个 nmr参数指定的东东啊。看main.py, 代码非常简单。 如果你有一堆干净高音质的样板语音，就把它们文件路径列到一个文本文件里，文本文件作为 --nmr的输入参数值。

列在一个文件里，具体的格式是啥样的？是一行一个文件名还是都放一行用逗号区分

**Comment by JohnHerry** [comment]
> > 你可以简单测试一个音频做样板语音的。样板语音就是那个 nmr参数指定的东东啊。看main.py, 代码非常简单。 如果你有一堆干净高音质的样板语音，就把它们文件路径列到一个文本文件里，文本文件作为 --nmr的输入参数值。
> 
> 列在一个文件里，具体的格式是啥样的？是一行一个文件名还是都放一行用逗号区分

I am sorry, but you should learn to read the source yourself. It is an OPEN SOURCE project, code speakers everything.
