### ISSUE TITLE
How do we interpret the scores (both MOS and NORESQA)?

### ISSUE THREAD

**Issue by vipasha-sanas** [facebookresearch/Noresqa#15]

**Comment by anuragkr90** [comment]
Interpretation of noresqa-MOS should be similar to conventional MOS. It's just that we are using NMR based approach to predict MOS. The NORESQA score is not bounded and is a relative score -- providing relative difference between the given NMR and the test signal. Please see the paper for details. You can also checkout this tutorial for more on NORESQA-MOS https://pytorch.org/audio/main/tutorials/squim_tutorial.html.
