### ISSUE TITLE
Is it a bug loading audio with fixed sample rate?

### ISSUE THREAD

**Issue by JohnHerry** [facebookresearch/Noresqa#6]
As we know librosa load audio with default sr=22050,  so if audio native is not, it will be resampled.
The code here:

     https://github.com/facebookresearch/Noresqa/blob/3de0457057bf06b9d55e00c976753ccaca7a0ffc/main.py#L101

I do not know why it is NOT

```
    audio, fs = librosa.load(path, sr=None)
```

It is a bug? or it is required by the pretrained model?

**Comment by argxkr** [comment]
There is a resampling happening to 16K. But yes, better to not read it at original sampling rate. Changed the code to reflect this.
